(ns sartar.frontend.constants)

(def runes {:movement "s"
            :air "g"
            :disorder "j"
            :harmony "l"
            :mastery "W"
            :water "w"
            :darkness "o"
            :illusion "i"
            :magicR "R"
            :earth "e"
            :stasis "c"
            :sky "."
            :fire "."
            :death "t"
            :truth "y"
            :life "x"
            :communication "h"
            :law "a"
            :spirit "b"
            :beast "B"
            :yinkin "Y"})
